### PR TITLE
feat: add databricks adapter

### PR DESCRIPTION
**Pull request by alexmalins**
WIP for when databricks adapter is released

cf. #374

### CODE REVIEW

**Comment by alexmalins** [comment]
Hey Ted! This one is good to go - we're live at https://pypi.org/project/harlequin-databricks/

**Comment by tconbeer** [comment]
Woohoo!

**Comment by alexmalins** [comment]
PR to add the adapter to conda-forge [here](https://github.com/conda-forge/staged-recipes/pull/25219)

**Comment by tconbeer** [comment]
I'm trying to rebase this, and at least on my machine, Poetry can't seem to create a new lockfile (it just stalls). If you could try to rebase and re-run `poetry lock`, that would be great. Otherwise I'll come back to this shortly, after merging in some other updates

**Comment by tconbeer** [comment]
superseded by https://github.com/tconbeer/harlequin/pull/449

**Pull request closed without merging**
